### ISSUE TITLE
Password reset journey crash

### ISSUE THREAD

**Issue by bengourley** [serby/ctrl#106]
Just went to have a look at the password reset journey, got this:

```
/Users/bengourley/Projects/control/bundles/administrator/lib/administratorModel.js:98
    return crypto.createHash('sha1').update(str).digest('hex');
           ^
ReferenceError: crypto is not defined
    at hashAdminState (/Users/bengourley/Projects/control/bundles/administrator/lib/administratorModel.js:98:12)
    at EventEmitter.requestPasswordChange (/Users/bengourley/Projects/control/bundles/administrator/lib/administratorModel.js:102:16)
    at /Users/bengourley/Projects/control/bundles/admin/controller.js:106:45
    at /Users/bengourley/Projects/control/lib/utils/mongodbCrudDelegate.js:213:9
    at /Users/bengourley/Projects/control/lib/utils/mongodbCrudDelegate.js:189:9
    at /Users/bengourley/Projects/control/node_modules/mongodb/lib/mongodb/cursor.js:129:9
    at /Users/bengourley/Projects/control/node_modules/mongodb/lib/mongodb/cursor.js:171:11
    at /Users/bengourley/Projects/control/node_modules/mongodb/lib/mongodb/cursor.js:463:35
    at Cursor.close (/Users/bengourley/Projects/control/node_modules/mongodb/lib/mongodb/cursor.js:682:5)
    at Cursor.nextObject (/Users/bengourley/Projects/control/node_modules/mongodb/lib/mongodb/cursor.js:463:17)
```

**Comment by tomgco** [comment]
This has now been fixed and merged into master and can be closed.
