### ISSUE TITLE
Crash after creating first admin user

### ISSUE THREAD

**Issue by robnoake** [serby/ctrl#3]
After the first administrator is created through /admin/setup, the application crashes with the following error:

```
Error: TypeError: undefined is not a function
    at Array.<anonymous> (/opt/projects/control/node_modules/mongodb/lib/mongodb/connection/server.js:168:49)
    at EventEmitter._tickCallback (node.js:126:26)
```

Output of npm list:

```
Control@0.0.1 /opt/projects/control
├── async@0.1.15
├─┬ cluster@0.7.7
│ ├── log@1.2.0
│ └── mkdirp@0.1.0
├── coffee-script@1.1.3
├── compress@0.1.9
├─┬ connect-mongodb@1.1.0
│ ├─┬ connect@1.5.1
│ │ └── qs@0.3.2
│ └── mongodb@0.9.7
├─┬ express@2.5.0
│ ├── connect@1.7.3
│ ├── mkdirp@0.0.7
│ └── qs@0.3.2
├── expresso@0.9.2
├── formidable@1.0.7
├── gm@0.5.0
├─┬ gzippo@0.0.6
│ └── mime@1.2.2
├─┬ jade@0.17.0
│ ├── commander@0.2.1
│ └── mkdirp@0.1.0
├── markdown@0.3.1
├── mime@1.2.4
├── mongodb@0.9.7-0
├─┬ nodemailer@0.2.3
│ └── mimelib-noiconv@0.1.4
├── piton-entity@0.1.2
├── piton-http-utils@0.0.1
├── piton-mixin@0.0.1
├── piton-pipe@0.0.2
├── piton-simplate@0.0.1
├── piton-string-utils@0.0.1
├── piton-validity@0.1.1
├── soda@0.2.4
├─┬ stylus@0.19.2
│ ├── cssom@0.2.0
│ ├── growl@1.1.0
│ └── mkdirp@0.0.7
├── underscore@1.2.1
└─┬ winston@0.5.6
  ├── colors@0.5.1
  ├── eyes@0.1.6
  ├─┬ loggly@0.3.9
  │ ├── request@2.2.0
  │ └── timespan@2.2.0
  ├── pkginfo@0.2.2
  └── stack-trace@0.0.6
```

**Comment by serby** [comment]
Thanks Rob

This is fixed in: 39a42c1
